In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.size

5

In [ ]:
a.ndim

1

In [ ]:
x=np.array([[3,4,6,7],[5,6,7,8],[8,9,10,11]])

In [ ]:
x

array([[ 3,  4,  6,  7],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [ ]:
x.shape

(3, 4)

In [ ]:
x.ndim

2

In [ ]:
x.size

12

In [ ]:
a=np.array([[[1,2],[3,4],[5,6]],
           [[1,2],[3,4],[5,6]],
            [[7,8],[9,4],[9,6]],
            [[1,2],[3,4],[5,6]]])

In [ ]:
a.size

24

In [ ]:
a.ndim

3

In [ ]:
a=np.zeros(5,dtype=int)

In [ ]:
a

array([0, 0, 0, 0, 0])

In [ ]:
a=np.zeros((3,4),dtype=int)

In [ ]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
a=np.ones((3,4),dtype=int)

In [ ]:
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
a=np.zeros((2,3,4),dtype=int)

In [ ]:
a

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
a=np.ones([2,3,4],dtype=int)

In [ ]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
#if we don't write dtype then output will be.......
a=np.ones([2,3,4])

In [ ]:
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
a=np.full([2,4],24)

In [ ]:
a

array([[24, 24, 24, 24],
       [24, 24, 24, 24]])

In [ ]:
#operations involved in
a=np.array([1,2,3])
b=np.array([1,2,3])

add=np.add(a,b)
add

array([2, 4, 6])

In [ ]:
a=np.array([1,8,3])
b=np.array([1,2,5])

sub=np.subtract(a,b)
sub

array([ 0,  6, -2])

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])

mul=np.multiply(a,b)
mul

array([1, 4, 9])

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])

div=np.divide(a,b)
div

array([1., 1., 1.])

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])

mod=np.mod(a,b)
mod

array([0, 0, 0])

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])

dot=np.dot(a,b)
dot

14

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])

power=np.power(a,b)
power

array([ 1,  4, 27])

In [ ]:
a=np.full([4,4],[71,72,71,72])
a

array([[71, 72, 71, 72],
       [71, 72, 71, 72],
       [71, 72, 71, 72],
       [71, 72, 71, 72]])

In [ ]:
a=np.full([4,4],71)
a

array([[71, 71, 71, 71],
       [71, 71, 71, 71],
       [71, 71, 71, 71],
       [71, 71, 71, 71]])

In [ ]:
b=np.array([[0,1,0,1],[0,1,0,1],[0,1,0,1],[0,1,0,1]])

In [ ]:
b

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [ ]:
np.add(a,b)

array([[71, 72, 71, 72],
       [71, 72, 71, 72],
       [71, 72, 71, 72],
       [71, 72, 71, 72]])

In [ ]:
a=np.full([6,7,7,9,5],[71,72,71,72,71])

In [ ]:
a

array([[[[[71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          ...,
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71]],

         [[71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          ...,
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71]],

         [[71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          ...,
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71]],

         ...,

         [[71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          ...,
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71]],

         [[71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          [71, 72, 71, 72, 71],
          ...,
          [71, 72, 71, 72, 71],
      